---
#
# Requirements:
# This playbook requires the extra var hello_name_extra_var to be set in AAP.
#
- name: Print hello message
  hosts: localhost
  
  tasks:

    - name: Print hello message 
      ansible.builtin.debug:
        msg: "Hello {{ hello_name_extra_var | default('world') }}!"

    


